<a href="https://colab.research.google.com/github/MiguelUTEC26/etl-data-pipeline/blob/main/polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/MiguelUTEC26/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

df = pd.read_csv(url)

df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [3]:
polizas = df.copy()

polizas.columns = polizas.columns.str.strip().str.lower()

for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].astype(str).str.strip()

polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)



polizas = polizas.drop_duplicates()

In [5]:
validos = polizas[
    polizas['fecha_emision'].notna() &
    polizas['id_cliente'].notna() &
    polizas['id_corredor'].notna() &
    polizas['id_aseguradora'].notna()&
    polizas['id_tipo_seguro'].notna()&
    polizas['prima'].notna()&
    polizas['comision'].notna()&
    polizas['monto_asegurado'].notna()
].copy()

rechazados = polizas[
    polizas['fecha_emision'].isna() |
    polizas['prima'].isna()|
    polizas['comision'].isna()|
    polizas['monto_asegurado'].isna()
].copy()

In [6]:
def motivo(row):

    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_emision_vacio")

    if pd.isna(row['prima']):
        motivos.append("prima_vacio")

    if pd.isna(row['comision']):
        motivos.append("comision_vacio")

    if pd.isna(row['monto_asegurado']):
        motivos.append("monto_asegurado_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [7]:
validos.to_csv("polizas_curated.csv", index=False)

rechazados.to_csv("polizas_rejects.csv", index=False)

In [8]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_c7ck_user:kFoJ2P6ViVJGqvzaVHFeHuuMqEThO1y3@dpg-d6qu3vc50q8c73bpda60-a.oregon-postgres.render.com/etl_seguros_c7ck"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [9]:
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [11]:
pd.read_sql(
"SELECT * FROM polizas_curated LIMIT 10",
engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,nan,184,42,15,2,"829,53",nan,139253.11
1,2,2026/02/16,2408,35,11,12,nan,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75
5,6,05-02-25,1295,17,1,1,943.49,nan,71968.43
6,7,02-09-25,1254,25,11,4,1400.82,188.40,258202.93
7,8,2026-01-11,887,77,3,8,1670.56,258.75,-
8,9,2025-02-28,1670,66,8,12,nan,"131,85",125804.84
9,10,2026/01/24,2281,69,13,3,791.38,"67,44",20710.00

In [12]:
pd.read_sql(
"SELECT * FROM polizas_rejects LIMIT 10",
engine
)

Empty DataFrame
Columns: [id_poliza, fecha_emision, id_cliente, id_corredor, id_aseguradora, id_tipo_seguro, prima, comision, monto_asegurado, motivo_rechazo]
Index: []